-minor fixes

diff --git a/contrib/libeufin-bank-dbconfig b/contrib/libeufin-bank-dbconfig
--- a/contrib/libeufin-bank-dbconfig
+++ b/contrib/libeufin-bank-dbconfig
@@ -99,11 +99,16 @@ then
         sudo -i -u postgres dropdb "$DBNAME"
     else
         echo "Database '$DBNAME' already exists."
-	if ! echo "GRANT ALL PRIVILEGES ON $DBNAME TO '$DBUSER'" \
+	if ! echo "GRANT ALL PRIVILEGES ON DATABASE $DBNAME TO \"$DBUSER\"" \
 		| sudo -i -u postgres psql "$DBNAME"
 	then
 	    echo "Failed to grant access to database '$DBNAME' to '$DBUSER'." 1>&2
 	    exit 1
+	fi
+	if ! echo "GRANT ALL PRIVILEGES ON SCHEMA _v TO \"$DBUSER\"" \
+		| sudo -i -u postgres psql "$DBNAME"
+	then
+	    echo "Failed to grant access to schema '_v' to '$DBUSER'. Maybe OK if it does not exist. Will continue." 1>&2
 	fi
     fi
 else
diff --git a/contrib/libeufin-nexus-dbconfig b/contrib/libeufin-nexus-dbconfig
--- a/contrib/libeufin-nexus-dbconfig
+++ b/contrib/libeufin-nexus-dbconfig
@@ -104,6 +104,11 @@ then
 	    echo "Failed to grant access to database '$DBNAME' to '$DBUSER'." 1>&2
 	    exit 1
 	fi
+	if ! echo "GRANT ALL PRIVILEGES ON SCHEMA _v TO \"$DBUSER\"" \
+		| sudo -i -u postgres psql "$DBNAME"
+	then
+	    echo "Failed to grant access to schema '_v' to '$DBUSER'. Maybe OK if it does not exist. Will continue." 1>&2
+	fi
     fi
 else
     echo "Creating database $DBNAME." 1>&2
